-- game.Players.PlayerAdded:Connect(function(player)
--     local leaderstats = Instance.new("Folder")
--     leaderstats.Name = "leaderstats"
--     leaderstats.Parent = player
--     local Wins = Instance.new("IntValue")
--     Wins.Name = "Wins"
--     Wins.Parent = leaderstats
-- end)
