-- local CS = game:GetService("CollectionService")
-- local RS = game:GetService("ReplicatedStorage")
-- local Sss = game:GetService("ServerScriptService")
-- local LetterFall = require(Sss.Source.LetterFall.LetterFall)
-- local LetterFallUtils = require(Sss.Source.LetterFall.LetterFallUtils)
-- local InitLetterRack = require(Sss.Source.LetterFall.InitLetterRack)
-- local InitWord = require(Sss.Source.LetterFall.InitWord)
-- local module = {}
-- function initLetterFall(miniGameState)
--     LetterFall.initGameToggle(miniGameState)
--     InitLetterRack.initLetterRack(miniGameState)
--     InitWord.initWords(miniGameState)
--     LetterFallUtils.styleLetterBlocks({
--         miniGameState = miniGameState,
--         availWords = miniGameState.words
--     })
-- end
-- module.initLetterFall = initLetterFall
-- return module
